Image.create!([
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2018/08/Wretched-Rush.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2018/08/I-II-III.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2018/09/Faces.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2018/08/Lets-Go.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2018/08/Lead-the-Way.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2018/08/Winding.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Shape-Study.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Eyes.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2015/11/Rume.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2015/12/Non-Hum.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Arcadeo-Overview.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2018/05/FrinPage.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2016/05/Levi.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Scenes-2017.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2016/01/Hair-Clip-3.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2016/01/A-Whisper.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2015/11/IoTaj.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Valley-of-Strings.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Lemon-Lime.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Arcadeo.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Vortex.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2017/11/Spect-Shot.jpg' },
  { url: 'http://www.maoartcorner.com/wp-content/uploads/2019/01/GlowFul.jpg' }
])
